FROM ghcr.io/linuxserver/baseimage-ubuntu:arm64v8-noble

# set labels
ARG IMAGE_BUILD_DATE
LABEL release_channel="stable"
LABEL org.opencontainers.image.authors="tibynx"
LABEL org.opencontainers.image.created="${IMAGE_BUILD_DATE}"
LABEL org.opencontainers.image.description="VS Code Tunnel inside a Docker container"
LABEL org.opencontainers.image.documentation="https://github.com/tibynx/code-tunnel/blob/main/README.md"
LABEL org.opencontainers.image.licenses="GPL-3.0-only"
LABEL org.opencontainers.image.source="https://github.com/tibynx/code-tunnel"
LABEL org.opencontainers.image.title="VS Code Tunnel"
LABEL org.opencontainers.image.url="https://github.com/tibynx/code-tunnel/packages"
LABEL org.opencontainers.image.vendor="tibynx"
LABEL org.opencontainers.image.base.name="ghcr.io/linuxserver/baseimage-ubuntu:arm64v8-noble"
LABEL org.opencontainers.image.base.documentation="https://github.com/linuxserver/docker-baseimage-ubuntu/blob/noble/README.md"

# branding
ENV LSIO_FIRST_PARTY=false

# set default tunnel name
ENV TUNNEL_NAME="code-tunnel"

# environment settings
ARG DEBIAN_FRONTEND="noninteractive"
ENV HOME="/config"

RUN \
  echo "**** install runtime dependencies ****" && \
  apt-get update && \
  apt-get install -y \
    git \
    gh \
    libatomic1 \
    nano \
    net-tools \
    curl \
    sudo \
    wget \
    gpg && \
  echo "**** install packages ****" && \
  wget -qO- https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > /tmp/packages.microsoft.gpg && \
  install -D -o root -g root -m 644 \
    /tmp/packages.microsoft.gpg \
    /usr/share/keyrings/packages.microsoft.gpg && \
  echo \
    "deb [arch=arm64,armhf signed-by=/usr/share/keyrings/packages.microsoft.gpg] \
    https://packages.microsoft.com/repos/code stable main" > /etc/apt/sources.list.d/vscode.list && \
  apt-get update -y && \
  apt-get install --no-install-recommends -y \
    code && \
  echo "**** clean up ****" && \
  apt-get clean && \
  rm -rf \
    /config/.cache \
    /var/lib/apt/lists/* \
    /var/tmp/* \
    /tmp/*

# add local files
COPY /root /
