name: "Build image"
on:
  schedule:
    - cron: "0 1 7 * *"
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  date:
    name: Get current date in RFC 3339
    runs-on: ubuntu-latest
    outputs:
      date: ${{ steps.date.outputs.date }}
    steps:
      - name: Get current date in RFC 3339
        id: date
        run: |
          echo "date=$(date --rfc-3339=seconds | sed 's/ /T/')" >> $GITHUB_OUTPUT

  version:
    name: Determine package version and image tag
    runs-on: ubuntu-latest
    outputs:
      package_version: ${{ steps.version.outputs.package_version }}
      image_tag: ${{ steps.version.outputs.image_tag }}
    steps:
      - name: Add Microsoft's APT repo for VS Code
        run: |
          sudo curl -vSLo \
            /etc/apt/keyrings/packages.microsoft.asc \
            https://packages.microsoft.com/keys/microsoft.asc
          echo \
            "deb [signed-by=/etc/apt/keyrings/packages.microsoft.asc] https://packages.microsoft.com/repos/code stable main" \
            | sudo tee -a /etc/apt/sources.list.d/microsoft.list
          sudo apt-get update -y

      - name: Get package version and set image tag 
        id: version
        run: |
          package_version_amd64=$(apt-cache policy code | awk -F': ' '/Candidate:/ {print $2}')
          [ -n "$package_version_amd64" ] || { echo "Failed to determine VS Code package version for amd64" >&2; exit 1; }
          package_version_arm64=$(apt-cache policy code:arm64 | awk -F': ' '/Candidate:/ {print $2}')
          [ -n "$package_version_arm64" ] || { echo "Failed to determine VS Code package version for arm64" >&2; exit 1; }
          package_version=$(echo "$package_version_amd64" | cut -d'-' -f1)
          image_tag=$package_version
          echo "package_version=$package_version" >> $GITHUB_OUTPUT
          echo "image_tag=$image_tag" >> $GITHUB_OUTPUT
          echo "Package Version amd64: $package_version_amd64"
          echo "Package Version arm64: $package_version_arm64"
          echo "Image Tag: $image_tag"

  build:
    name: Build and push image
    runs-on: ubuntu-latest
    needs: [date, version]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push image for amd64/arm64
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          file: ./Dockerfile
          push: true
          build-args: |
            IMAGE_BUILD_DATE=${{ needs.date.outputs.date }}
            INSTALL_VERSION=${{ needs.version.outputs.package_version }}
          tags: |
            ghcr.io/${{ github.repository_owner }}/code-tunnel:latest
            ghcr.io/${{ github.repository_owner }}/code-tunnel:${{ needs.version.outputs.image_tag }}
            ${{ vars.DOCKERHUB_USERNAME }}/code-tunnel:latest
            ${{ vars.DOCKERHUB_USERNAME }}/code-tunnel:${{ needs.version.outputs.image_tag }}
          labels: |
            org.opencontainers.image.ref.name=${{ github.ref }}
            org.opencontainers.image.revision=${{ github.sha }}
            org.opencontainers.image.version=${{ needs.version.outputs.package_version }}
